.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MGR\-LDAPSYNC" "1" "2019-10-25" "" ""
.
.SH "NAME"
\fBmgr\-ldapsync\fR \- Utility to synchronise users between LDAP of your choice and the Uyuni server
.
.SH "SYNOPSIS"
\fBmgr\-ldapsync\fR [option]
.
.SH "DESCRIPTION"
\fBmgr\-ldapsync(1)\fR is a program that synchronises LDAP users with the Uyuni server\. It will add users from LDAP, update them if their attributes changed or remove them from Uyuni\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR, \fB\-\-config\fR=[value]
Specifiy an optional configuration file\. Default configuration file is: \fB/etc/rhn/ldapsync\.conf\fR
.
.TP
\fB\-o\fR, \fB\-\-overview\fR
Overview or "dry run" mode\. In this case the \fBmgr\-ldapsync\fR will only show you what is going to change, but will not perform any real actions\.
.
.TP
\fB\-s\fR, \fB\-\-sync\fR
Perform an actual synchronisation\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows help\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Shows current version of the \fBmgr\-ldapsync\fR\.
.
.SH "REQUIREMENTS"
LDAP is very flexible and easy to customise\. Because of this, \fBmgr\-ldapsync\fR allows users to adjust the configuration for the existing LDAP schema\. If not specified otherwise, default configuration file is first looked up in \fB/etc/rhn/ldapsync\.conf\fR\.
.
.P
There are certain requirements how to manage users in LDAP so they are synchronised correctly with the Uyuni server:
.
.IP "1." 4
There should be either at least one \fIgroup\fR of object class \fBgroupOfNames\fR or at least one \fIrole\fR of object class \fBorganizationalRole\fR\. In case of Active Directory, \fIgroup\fR object class should be called \fBgroup\fR\.
.
.IP "2." 4
Each group should have at least one attribute \fBmember\fR with a valid DN of an actual user\.
.
.IP "3." 4
In case a groups are not used, a role has to have at least one attribute \fBroleOccupant\fR with the valid DN of an actual user\.
.
.IP "4." 4
There should be an accessible DN for all users in the LDAP database\.
.
.IP "" 0
.
.P
Each user should have the following \fBmandatory\fR attributes:
.
.IP "\(bu" 4
\fBuid\fR
.
.IP "\(bu" 4
\fBcn\fR
.
.IP "\(bu" 4
\fBname\fR or \fBgivenName\fR (optional, if \fBcn\fR has name and second name)
.
.IP "\(bu" 4
\fBsn\fR (optional, if \fBcn\fR has name and second name)
.
.IP "\(bu" 4
\fBmail\fR
.
.IP "" 0
.
.P
\fBIMPORTANT:\fR The \fBmgr\-ldapsync\fR is not expected to work properly, if the requirements above are not met\.
.
.SH "CONFIGURATION"
Configuration file should be a valid YAML file\.
.
.P
It has two main sections at the root:
.
.IP "1." 4
\fBdirectory\fR: Directory describes all the configuration, required by the LDAP server\.
.
.IP "2." 4
\fBrpc\fR: This section describes all the configuration, required by Uyuni server\.
.
.IP "" 0
.
.P
The \fBdirectory\fR section has the following attributes:
.
.TP
\fBudn\fR (string)
A user\'s DN for the directory to connect\. Example: \fBuid=admin,ou=system\fR\.
.
.TP
\fBpassword\fR (string)
LDAP authentication password for the \fBudn\fR above\.
.
.TP
\fBhost\fR (string)
Fully qualified domain name of the LDAP server\.
.
.TP
\fBport\fR (integer, optional)
Port on which LDAP server is running\. By default it is \fB389\fR\.
.
.TP
\fBallusers\fR (string)
DN for all the users subtree\. Example: \fBou=users,dc=example,dc=com\fR\.
.
.P
The \fBdirectory\fR section has also the following directives:
.
.IP "1." 4
\fBfrozen\fR (map, mandatory)\. This is a list of Uyuni user IDs that \fBmgr\-ldapsync\fR should \fIcompletely\fR ignore\. Any user ID, specified in this directive will always exclude any user in the Uyuni server from being affected by LDAP operations\. This is usually the main "static" administrator account or an emergency login\. This directive is mandatory and LDAP sync will refuse to work if you have no at least one frozen user with \fBorg_admin\fR permissions assigned\.
.
.IP "2." 4
\fBgroups\fR or \fBroles\fR map, at least one of them must be present\. \fBEither\fR directive is \fBmandatory\fR to specify, in order to properly manage Uyuni roles\. Both directives has the same structure a list of Uyuni roles, attached to a CN in the LDAP\. See "examples" section below for more details:
.
.IP "" 0
.
.IP "" 4
.
.nf

   roles|groups:
     cn:
       \- role
       \- role
       \- role
       \.\.\.
.
.fi
.
.IP "" 0
.
.P
The \fBrpc\fR section contains all the necessary information for XML\-RPC API of Uyuni server:
.
.TP
\fBurl\fR (string)
URL of the XML\-RPC API for the Uyuni server\. It should contain a schema in order to specify if SSL/TLS is required\.
.
.TP
\fBcheckssl\fR (boolean, optional, default \fBtrue\fR)
A boolean true/false option to allow SSL connection to the URL without proper SSL certificate\.
.
.TP
\fBuser\fR (string)
Username of the Uyuni administrator with the \fBorg_admin\fR or \fBsatellite_admin\fR role\. This is usually the user was created at the very first start\.
.
.TP
\fBpassword\fR (string)
Password for the Uyuni administrator username\.
.
.SH "LIST OF UYUNI ROLES"
Uyuni server supports the following roles:
.
.TP
\fBorg_admin\fR
Administrative role\. Appears as "Organization Administrator"\. It can administer the entire Uyuni server across all the organisations\.
.
.TP
\fBsatellite_admin\fR
Administrative role\. Appears as "SUSE Manager Administrator"\. It can administer the entire Uyuni server, but only within the given organisation\.
.
.TP
\fBconfig_admin\fR
Appears as "Configuration Administrator" and gives user to configure individual system profiles, channels and certain configuration files\.
.
.TP
\fBchannel_admin\fR
Appears as "Channel Administrator" and gives user ability to add, modify and delete channels\.
.
.TP
\fBsystem_group_admin\fR
Appears as "System Group Administrator" and gives user to access systems section\.
.
.TP
\fBactivation_key_admin\fR
Appears as "Activation Key Administrator" and gives user the control over activation keys, subscriptions etc\.
.
.TP
\fBimage_admin\fR
Appears as "Image Administrator" and is related to OS images administration to build them, store in the registry etc\.
.
.SH "EXAMPLES"
\fBExample: map LDAP roles\fR
.
.P
To map a \fBconfig_admin\fR and \fBchannel_group_admin\fR Uyuni roles to a \fBorganizationalRole\fR object in the LDAP, do the following:
.
.IP "1." 4
Create a role group in the LDAP with the class \fBorganizationalRole\fR\.
.
.IP "2." 4
Add at least one user to that role that is supposed to have it with the attribute \fBroleOccupant\fR\.
.
.IP "3." 4
Create the following configuration in the \fB/etc/rhn/ldapsync\.conf\fR file:
.
.IP "" 0
.
.IP "" 4
.
.nf

  directory:
    roles:
      cn=admins,ou=groups,dc=example,dc=com
        \- config_admin
        \- channel_group_admin
.
.fi
.
.IP "" 0
.
.P
The configuration above will assign a \fBconfig_admin\fR and a \fBchannel_group_admin\fR Uyuni roles to the CN of a role group in LDAP\.
.
.P
\fBExample: map LDAP groups\fR
.
.P
To map a \fBconfig_admin\fR and \fBchannel_group_admin\fR Uyuni roles to a group is very similar to \fBorganizationalRole\fR scenario above, with few differences:
.
.IP "1." 4
Create a group in the LDAP with the class \fBgroupOfNames\fR (POSIX) or \fBgroup\fR (Active Directory)\.
.
.IP "2." 4
Add at least one user to that group with the attribute \fBmember\fR\. NOTE: User attributes should meet the requirements, described in "Requirements" section above\.
.
.IP "3." 4
Create the following configuration in the \fB/etc/rhn/ldapsync\.conf\fR file:
.
.IP "" 0
.
.IP "" 4
.
.nf

   directory:
     groups:
       cn=admins,ou=groups,dc=example,dc=com
         \- config_admin
         \- channel_group_admin
.
.fi
.
.IP "" 0
.
.P
The configuration above will assign a \fBconfig_admin\fR and a \fBchannel_group_admin\fR Uyuni roles to the CN of a group in LDAP\.
.
.P
For more information, look into the configuration file itself and follow the examples there\.
.
.SH "DIAGNOSTICS"
\fBmgr\-ldapsync\fR returns zero on normal operation, non\-zero otherwise\.
.
.SH "AUTHOR"
Bo Maryniuk \fIbo@suse\.de\fR
.
.SH "SEE ALSO"
pam
